server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.161.101:3306/leyou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 159637428
    driver-class-name: org.gjt.mm.mysql.Driver
  rabbitmq:
    host: 192.168.161.101
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.lollipop.item.pojo