server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ly:
  jwt:
    secret: leyou@Login(Auth}*^31)&lollipop% # 登录校验的密钥
    pubKeyPath: G:/test/rsa.pub # 公钥地址
    priKeyPath: G:/test/rsa.pri # 私钥地址
    expire: 1800 # 过期时间,单位秒
    cookieName: LY_TOKEN