server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.161.101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: G:/test/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称