spring:
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      #create：每次运行程序时，都会重新创建表，故而数据会丢失
      #create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
      #upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
      #validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
      #none: 禁用DDL处理
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root

  application:
      name: chat-one
  thymeleaf:
      cache: false
      enabled: true
      encoding: utf-8

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    com.jsc: debug